// Public URL codes stay stable; CMS locale codes follow Payload's configuration.
export const locales = [
  ['en', 'en', 'English', 'All Astra prompts', 'Original post', 'Source code', 'Live demo', 'View detail', 'Watch video', 'Prompt', 'Featured projects', 'Browse examples', 'Back to examples', 'A starting point for your next game, scene or interactive world.'],
  ['zh', 'zh-CN', '简体中文', '全部 Astra 提示词', '查看原帖', '项目源码', '在线演示', '查看详情', '观看视频', '提示词', '精选作品', '浏览案例', '返回案例导航', '为你的下一个游戏、场景或交互世界找到灵感。'],
  ['zh-Hant', 'zh-TW', '繁體中文', '全部 Astra 提示詞', '查看原文', '專案原始碼', '線上展示', '查看詳情', '觀看影片', '提示詞', '精選作品', '瀏覽案例', '返回案例導覽', '為你的下一個遊戲、場景或互動世界尋找靈感。'],
  ['ja', 'ja', '日本語', 'Astra の全プロンプト', '元の投稿', 'ソースコード', 'デモ', '詳細を見る', '動画を見る', 'プロンプト', '注目の作品', '作例を見る', '作例一覧に戻る', '次のゲーム、シーン、インタラクティブな世界づくりのヒントに。'],
  ['ko', 'ko', '한국어', '모든 Astra 프롬프트', '원본 게시물', '소스 코드', '데모', '자세히 보기', '동영상 보기', '프롬프트', '추천 작품', '사례 둘러보기', '사례 목록으로', '다음 게임, 장면, 인터랙티브 세계를 위한 아이디어를 찾아보세요.'],
  ['es', 'es', 'Español', 'Todos los prompts de Astra', 'Publicación original', 'Código fuente', 'Demo en línea', 'Ver detalles', 'Ver vídeo', 'Prompt', 'Proyectos destacados', 'Explorar ejemplos', 'Volver a los ejemplos', 'Un punto de partida para tu próximo juego, escena o mundo interactivo.'],
  ['pt', 'pt-BR', 'Português', 'Todos os prompts do Astra', 'Publicação original', 'Código-fonte', 'Demonstração', 'Ver detalhes', 'Ver vídeo', 'Prompt', 'Projetos em destaque', 'Explorar exemplos', 'Voltar aos exemplos', 'Um ponto de partida para seu próximo jogo, cena ou mundo interativo.'],
  ['de', 'de', 'Deutsch', 'Alle Astra-Prompts', 'Originalbeitrag', 'Quellcode', 'Live-Demo', 'Details ansehen', 'Video ansehen', 'Prompt', 'Ausgewählte Projekte', 'Beispiele ansehen', 'Zurück zu den Beispielen', 'Ideen für dein nächstes Spiel, deine nächste Szene oder interaktive Welt.'],
  ['fr', 'fr', 'Français', 'Tous les prompts Astra', 'Publication originale', 'Code source', 'Démo', 'Voir les détails', 'Voir la vidéo', 'Prompt', 'Projets à découvrir', 'Parcourir les exemples', 'Retour aux exemples', 'Un point de départ pour votre prochain jeu, scène ou monde interactif.'],
  ['it', 'it', 'Italiano', 'Tutti i prompt Astra', 'Post originale', 'Codice sorgente', 'Demo', 'Vedi dettagli', 'Guarda il video', 'Prompt', 'Progetti in evidenza', 'Esplora gli esempi', 'Torna agli esempi', 'Un punto di partenza per il tuo prossimo gioco, scena o mondo interattivo.'],
  ['ru', 'ru', 'Русский', 'Все промпты Astra', 'Исходная публикация', 'Исходный код', 'Демо', 'Подробнее', 'Смотреть видео', 'Промпт', 'Избранные проекты', 'Посмотреть примеры', 'Назад к примерам', 'Идеи для вашей следующей игры, сцены или интерактивного мира.'],
  ['tr', 'tr', 'Türkçe', 'Tüm Astra istemleri', 'Orijinal gönderi', 'Kaynak kodu', 'Canlı demo', 'Ayrıntıları görüntüle', 'Videoyu izle', 'İstem', 'Öne çıkan projeler', 'Örnekleri keşfet', 'Örneklere dön', 'Bir sonraki oyununuz, sahneniz veya etkileşimli dünyanız için bir başlangıç noktası.'],
  ['uk', 'uk', 'Українська', 'Усі промпти Astra', 'Оригінальний допис', 'Вихідний код', 'Демо', 'Докладніше', 'Переглянути відео', 'Промпт', 'Вибрані проєкти', 'Переглянути приклади', 'Назад до прикладів', 'Ідеї для вашої наступної гри, сцени або інтерактивного світу.'],
  ['vi', 'vi', 'Tiếng Việt', 'Tất cả prompt Astra', 'Bài đăng gốc', 'Mã nguồn', 'Bản demo', 'Xem chi tiết', 'Xem video', 'Prompt', 'Dự án nổi bật', 'Khám phá ví dụ', 'Về danh sách ví dụ', 'Khởi đầu cho trò chơi, cảnh 3D hoặc thế giới tương tác tiếp theo của bạn.'],
].map(([code, cms, name, title, source, repository, demo, detail, video, prompt, featured, browse, back, intro]) => ({ code, cms, name, title, source, repository, demo, detail, video, prompt, featured, browse, back, intro }))
export const modelSlug = 'gpt-6-astra'
export const repository = 'TripoGrowthLab/awesome-astra-prompts'
